# Generated by Django 3.1.1 on 2020-10-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idcard_no', models.IntegerField()),
                ('id_type', models.CharField(choices=[('1', 'PAN'), ('2', 'Aadhar'), ('3', 'VoterID'), ('4', 'Others')], max_length=1)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('meet_with', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegisteredUsers', to='myuserapp.userregister')),
            ],
        ),
    ]
